version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: barberia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barberia_db
      MYSQL_USER: barber_user
      MYSQL_PASSWORD: barber_password
    ports:
      - "3306:3306"
    volumes:
      - db_data_v2:/var/lib/mysql

volumes:
  db_data_v2:
